/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-12-07 00:42:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jquery.datatables.model.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Applying JQuery DataTables plugin in the Java Server application</title>\r\n");
      out.write("        <link href=\"media/dataTables/demo_page.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"media/dataTables/demo_table.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"media/dataTables/demo_table_jui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"media/themes/base/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        <link href=\"media/themes/smoothness/jquery-ui-1.7.2.custom.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        <script src=\"scripts/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script src=\"scripts/jquery.dataTables.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $(\"#companies\").dataTable({\r\n");
      out.write("                \"sPaginationType\": \"full_numbers\",\r\n");
      out.write("                \"bJQueryUI\": true\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"dt_example\">\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("        \t<div id=\"links\">\r\n");
      out.write("        \t    Client side processing | <a href=\"plugins.jsp\">Client side processing with additional plugins</a><br/>\r\n");
      out.write("        \t\t<a href=\"index.html\">Server-side processing with matrix source</a> | <a href=\"objects.html\">Server-side processing with object source</a>\r\n");
      out.write("        \t\t<br/>\r\n");
      out.write("        \t</div>\r\n");
      out.write("            <div id=\"demo_jui\">\r\n");
      out.write("\t\t        <table id=\"companies\" class=\"display\">\r\n");
      out.write("\t\t            <thead>\r\n");
      out.write("\t\t                <tr>\r\n");
      out.write("\t\t                    <th>Company name</th>\r\n");
      out.write("\t\t                    <th>Address</th>\r\n");
      out.write("\t\t                    <th>Town</th>\r\n");
      out.write("\t\t                </tr>\r\n");
      out.write("\t\t            </thead>\r\n");
      out.write("\t\t            <tbody>\r\n");
      out.write("\t\t          \t\t");
 for(Company c: DataRepository.GetCompanies()){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t  <tr>\n");
      out.write("\t\t\t\t\t\t    <td>");
      out.print(c.getName());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t    <td>");
      out.print(c.getAddress());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t    <td>");
      out.print(c.getTown());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t            </tbody>\r\n");
      out.write("\t\t        </table>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
